version: "3.9"

services:
  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

  server:
    container_name: node
    build: .
    environment:
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
volumes:
  mongo_db: {}
